/**
 * Lightweight test-data factory. Generates randomised but valid product data
 * so tests do not collide and remain independent.
 */

export interface NewProduct {
  name: string
  sku: string
  category: 'Electronics' | 'Furniture' | 'Groceries' | 'Clothing' | 'Tools' | ''
  quantity: number
  price: number
  supplier: string
  description: string
  notify: boolean
}

const categories = ['Electronics', 'Furniture', 'Groceries', 'Clothing', 'Tools'] as const
const suppliers = ['TechSupply Co', 'Comfort Living', 'FreshFarms', 'StyleHub', 'BuildIt Ltd']
const prefixes: Record<(typeof categories)[number], string> = {
  Electronics: 'ELE',
  Furniture: 'FUR',
  Groceries: 'GRO',
  Clothing: 'CLO',
  Tools: 'TOO',
}

function randomInt(min: number, max: number): number {
  return Math.floor(Math.random() * (max - min + 1)) + min
}

function pick<T>(arr: readonly T[]): T {
  return arr[randomInt(0, arr.length - 1)]
}

/** Generate a valid product payload, optionally overriding any field. */
export function buildProduct(overrides: Partial<NewProduct> = {}): NewProduct {
  const category = (overrides.category as (typeof categories)[number]) || pick(categories)
  const sku = `${prefixes[category]}-${randomInt(1000, 9999)}`
  return {
    name: `Test Product ${randomInt(1000, 9999)}`,
    sku,
    category,
    quantity: randomInt(1, 500),
    price: Number((Math.random() * 500 + 1).toFixed(2)),
    supplier: pick(suppliers),
    description: 'Auto-generated by the data factory.',
    notify: Math.random() > 0.5,
    ...overrides,
  }
}

/** Generate a unique-ish email for form testing. */
export function randomEmail(): string {
  return `user_${Date.now()}_${randomInt(100, 999)}@example.com`
}
